/** Deterministic 30 second, six-source EDM fixture for the isolation gate. */
import type { StemId } from './types';
import { addKick, addNoiseBurst, addSupersaw, addVocal, prng } from './testAudioGenerator';
import { compress, saturate, simpleReverb, softLimit, type StereoBuffer } from './mixEffects';
export const TEST_SEED = 20260913;
export const GOLD_STANDARD_STEMS: StemId[] = ['vocals', 'drums', 'bass', 'synth', 'percussion', 'fx'];
export interface GoldStandardSegment { id: string; title: string; startSeconds: number; endSeconds: number; description: string; activeStems: StemId[]; overlapPairs: [StemId, StemId][]; }
export interface GoldStandardTrack { sampleRate: number; channels: 2; frames: number; seconds: number; seed: number; bpm: number; stemOrder: StemId[]; stems: Map<StemId, Float32Array>; mix: Float32Array; masterBusMix: Float32Array; segments: GoldStandardSegment[]; transientFrames: { stemId: StemId; frame: number; kind: string }[]; meta: Record<string, unknown>; }
function addTone(target: Float32Array, frames: number, sr: number, start: number, len: number, freq: number, gain: number, pan = 0, decay = 0.3): void { const lg = 1 - Math.max(0, pan), rg = 1 + Math.min(0, pan); for (let i = 0; i < len && start + i < frames; i++) { const t = i / sr, e = Math.min(1, t / .008) * Math.exp(-t * decay), v = Math.sin(2 * Math.PI * freq * t) * e * gain; target[(start + i) * 2] += v * lg; target[(start + i) * 2 + 1] += v * rg; } }
function addPerc(target: Float32Array, frames: number, sr: number, start: number, freq: number, gain: number, pan: number): void { addTone(target, frames, sr, start, Math.floor(sr * .12), freq, gain, pan, 22); }
function addFx(target: Float32Array, frames: number, sr: number, start: number, len: number, random: () => number): void { let l = 0, r = 0; for (let i = 0; i < len && start + i < frames; i++) { const t = i / sr, p = i / len, e = p * Math.exp(-t * 1.5); l += ((random() * 2 - 1) * .12 - l) * .08; r += ((random() * 2 - 1) * .12 - r) * .08; target[(start + i) * 2] += l * e; target[(start + i) * 2 + 1] += r * e; } }
function addHat(target: Float32Array, frames: number, sr: number, start: number, random: () => number, pan: number): void { const len = Math.floor(sr * .05), lg = 1 - Math.max(0, pan), rg = 1 + Math.min(0, pan); let pL = 0, pR = 0, prevL = 0, prevR = 0; for (let i = 0; i < len && start + i < frames; i++) { const rawL = random() * 2 - 1, rawR = random() * 2 - 1, l = .9 * (pL + rawL * .35 - prevL), r = .9 * (pR + rawR * .35 - prevR); prevL = rawL * .35; prevR = rawR * .35; pL = l; pR = r; const e = Math.exp(-i / sr * 55); target[(start + i) * 2] += l * e * lg; target[(start + i) * 2 + 1] += r * e * rg; } }
export interface GoldStandardOptions { seed?: number; sampleRate?: number; bpm?: number; }
export function generateGoldStandardTrack(options: GoldStandardOptions = {}): GoldStandardTrack {
  const sampleRate = options.sampleRate ?? 44100, bpm = options.bpm ?? 128, seed = options.seed ?? TEST_SEED, seconds = 30, frames = Math.floor(sampleRate * seconds), random = prng(seed);
  const stems = new Map<StemId, Float32Array>(GOLD_STANDARD_STEMS.map((id) => [id, new Float32Array(frames * 2)]));
  const vocals = stems.get('vocals')!, drums = stems.get('drums')!, bass = stems.get('bass')!, synth = stems.get('synth')!, percussion = stems.get('percussion')!, fx = stems.get('fx')!;
  const beat = Math.floor(sampleRate * 60 / bpm), frameAt = (s: number) => Math.floor(s * sampleRate), transientFrames: GoldStandardTrack['transientFrames'] = [];
  const beatRange = (from: number, to: number, fn: (frame: number, n: number) => void) => { let n = 0; for (let f = frameAt(from); f < frameAt(to); f += beat) fn(f, n++); };
  // 0-5: deliberately overlapping kick, sub and bass.
  beatRange(0, 5, (f, n) => { addKick(drums, frames, sampleRate, f, 1); transientFrames.push({ stemId: 'drums', frame: f, kind: 'kick' }); addTone(bass, frames, sampleRate, f, beat, [41.2, 41.2, 55, 36.7][n % 4], .45, 0, 1.1); addTone(bass, frames, sampleRate, f + Math.floor(beat / 2), beat / 2, [82.4, 82.4, 110, 73.4][n % 4], .28, 0, 1.4); transientFrames.push({ stemId: 'bass', frame: f, kind: 'sub-attack' }); });
  // 5-10: bass and low synth share their fundamentals.
  beatRange(5, 10, (f, n) => { addKick(drums, frames, sampleRate, f, .98); const root = [55, 55, 73.4, 49][n % 4]; addTone(bass, frames, sampleRate, f, beat, root, .4, 0, .9); addSupersaw(synth, frames, sampleRate, root * 2, f + Math.floor(beat / 4), Math.floor(beat * .65), .24, .6); transientFrames.push({ stemId: 'drums', frame: f, kind: 'kick' }, { stemId: 'bass', frame: f, kind: 'bass-attack' }, { stemId: 'synth', frame: f + Math.floor(beat / 4), kind: 'pluck-attack' }); });
  // 10-15: vocal harmonics and synth formants overlap in the mid band.
  const vocalFreqs = [261.63, 293.66, 329.63, 246.94]; beatRange(10, 15, (f, n) => { const v = vocalFreqs[n % 4]; addVocal(vocals, frames, sampleRate, v, f, Math.floor(beat * 1.7), .7); for (const ratio of [1, 1.5, 2]) addSupersaw(synth, frames, sampleRate, v * ratio, f, Math.floor(beat * 1.8), .1, .7); transientFrames.push({ stemId: 'vocals', frame: f, kind: 'vocal-onset' }); });
  // 15-20: high percussion and a wide delayed synth.
  for (let f = frameAt(15), n = 0; f < frameAt(20); f += Math.floor(beat / 4), n++) { addHat(percussion, frames, sampleRate, f, random, n % 2 ? .6 : -.6); if (n % 4 === 2) addPerc(percussion, frames, sampleRate, f, 320 + n % 3 * 40, .35, n % 8 < 4 ? -.8 : .8); transientFrames.push({ stemId: 'percussion', frame: f, kind: 'hat' }); }
  beatRange(15, 20, (f, n) => { addSupersaw(synth, frames, sampleRate, [220, 246.94, 196][n % 3], f, beat * 1.5, .18, .95); });
  // 20-30: dense sections contain all principal musical families.
  for (let f = frameAt(20), n = 0; f < frames; f += beat, n++) { addKick(drums, frames, sampleRate, f, 1); addNoiseBurst(drums, frames, sampleRate, f + Math.floor(beat / 2), Math.floor(sampleRate * .04), .35, .7, random); addTone(bass, frames, sampleRate, f, beat, [55, 55, 73.4, 49][n % 4], .4, 0, .8); addSupersaw(synth, frames, sampleRate, [220, 220, 293.66, 196][n % 4], f, beat, .13, .8); if (n % 2 === 0) addVocal(vocals, frames, sampleRate, 293.66, f, Math.floor(beat * .9), .35); for (let h = 0; h < 4; h++) addHat(percussion, frames, sampleRate, f + h * Math.floor(beat / 4), random, h % 2 ? .45 : -.45); transientFrames.push({ stemId: 'drums', frame: f, kind: 'kick' }); }
  addFx(fx, frames, sampleRate, frameAt(23.2), Math.floor(sampleRate * 1.8), random); addFx(fx, frames, sampleRate, frameAt(25), Math.floor(sampleRate * .7), random); transientFrames.push({ stemId: 'fx', frame: frameAt(25), kind: 'impact' });
  // Remove tiny DC offsets before constructing the exact linear mix.
  for (const data of stems.values()) { let sum = 0; for (const v of data) sum += v; const dc = sum / data.length; for (let i = 0; i < data.length; i++) data[i] -= dc; }
  const raw = new Float32Array(frames * 2); for (const data of stems.values()) for (let i = 0; i < raw.length; i++) raw[i] += data[i]; let peak = 0; for (const v of raw) peak = Math.max(peak, Math.abs(v)); const gain = peak > .891 ? .891 / peak : 1; const mix = new Float32Array(raw.length); for (let i = 0; i < raw.length; i++) mix[i] = raw[i] * gain; for (const data of stems.values()) for (let i = 0; i < data.length; i++) data[i] *= gain;
  const segments: GoldStandardSegment[] = [
    { id: 'sub-overlap', title: 'Kick + Subbass', startSeconds: 0, endSeconds: 5, description: 'Kick und Subbass im selben tiefen Frequenzbereich.', activeStems: ['drums', 'bass'], overlapPairs: [['drums', 'bass']] },
    { id: 'kick-bass-synth', title: 'Kick + Bass + Synth', startSeconds: 5, endSeconds: 10, description: 'Bass und Synth überlappen im unteren/mittleren Bereich.', activeStems: ['drums', 'bass', 'synth'], overlapPairs: [['bass', 'synth'], ['drums', 'bass']] },
    { id: 'vocal-synth', title: 'Vocal + Synth', startSeconds: 10, endSeconds: 15, description: 'Vocal und Synth teilen sich den Formantbereich.', activeStems: ['vocals', 'synth'], overlapPairs: [['vocals', 'synth']] },
    { id: 'hats-percussion-stereo', title: 'Hi-Hats + Percussion + Stereo Synth', startSeconds: 15, endSeconds: 20, description: 'Breite Synths und hochfrequente Percussion.', activeStems: ['percussion', 'synth'], overlapPairs: [['percussion', 'synth']] },
    { id: 'dense-edm', title: 'Dense EDM Section', startSeconds: 20, endSeconds: 25, description: 'Alle Quellen mit Pumping und FX.', activeStems: GOLD_STANDARD_STEMS, overlapPairs: [['drums', 'bass'], ['bass', 'synth'], ['vocals', 'synth'], ['percussion', 'synth'], ['fx', 'vocals']] },
    { id: 'master-bus', title: 'Master-Bus-Simulation', startSeconds: 25, endSeconds: 30, description: 'Voller Mix als Grundlage für Master-Bus-Varianten.', activeStems: ['vocals', 'drums', 'bass', 'synth', 'percussion'], overlapPairs: [['drums', 'bass']] },
  ];
  const busInput: StereoBuffer = { data: new Float32Array(mix), sampleRate, frames };
  const masterBusMix = softLimit(simpleReverb(saturate(compress(busInput, { thresholdDb: -20, ratio: 6, attackMs: 5, releaseMs: 100, makeupDb: 7 }), 1.5), { wet: .15, decay: .5, predelayMs: 10 }), -.3).data;
  return { sampleRate, channels: 2, frames, seconds, seed, bpm, stemOrder: GOLD_STANDARD_STEMS, stems, mix, masterBusMix, segments, transientFrames, meta: { seed, bpm, gain, stemCount: 6, busChain: 'compression+saturation+reverb+limiting' } };
}
