export interface StereoBuffer { data: Float32Array; sampleRate: number; frames: number; }
function clone(b: StereoBuffer): StereoBuffer { return { data: new Float32Array(b.data), sampleRate: b.sampleRate, frames: b.frames }; }
export function peakOf(data: Float32Array): number { let p = 0; for (const v of data) p = Math.max(p, Math.abs(v)); return p; }
export function dbToLinear(db: number): number { return 10 ** (db / 20); }
export function linearToDb(value: number): number { return 20 * Math.log10(Math.max(1e-12, Math.abs(value))); }
export function peakNormalize(buffer: StereoBuffer, targetDb: number): StereoBuffer { const out = clone(buffer), gain = dbToLinear(targetDb) / Math.max(1e-9, peakOf(out.data)); for (let i = 0; i < out.data.length; i++) out.data[i] *= gain; return out; }
export interface CompressorOptions { thresholdDb: number; ratio: number; attackMs: number; releaseMs: number; makeupDb: number; }
export function compress(buffer: StereoBuffer, o: CompressorOptions): StereoBuffer { const out = clone(buffer), attack = Math.exp(-1 / Math.max(1, o.attackMs / 1000 * buffer.sampleRate)), release = Math.exp(-1 / Math.max(1, o.releaseMs / 1000 * buffer.sampleRate)); let env = 0; for (let f = 0; f < buffer.frames; f++) { const l = out.data[f * 2] || 0, r = out.data[f * 2 + 1] || 0, level = Math.hypot(l, r) / Math.sqrt(2); env = level > env ? attack * env + (1 - attack) * level : release * env + (1 - release) * level; const db = linearToDb(env), reduction = db > o.thresholdDb ? (o.thresholdDb - db) * (1 - 1 / Math.max(1, o.ratio)) : 0, gain = dbToLinear(reduction + o.makeupDb); out.data[f * 2] = l * gain; out.data[f * 2 + 1] = r * gain; } return out; }
export function softLimit(buffer: StereoBuffer, ceilingDb: number): StereoBuffer { return compress(buffer, { thresholdDb: ceilingDb - .2, ratio: 20, attackMs: .3, releaseMs: 50, makeupDb: 0 }); }
export function saturate(buffer: StereoBuffer, drive: number): StereoBuffer { const out = clone(buffer), norm = Math.tanh(Math.max(.01, drive)); for (let i = 0; i < out.data.length; i++) out.data[i] = Math.tanh(out.data[i] * drive) / norm; return out; }
export function hardClip(buffer: StereoBuffer, ceiling: number): StereoBuffer { const out = clone(buffer); for (let i = 0; i < out.data.length; i++) out.data[i] = Math.max(-ceiling, Math.min(ceiling, out.data[i])); return out; }
export function stereoWidth(buffer: StereoBuffer, factor: number): StereoBuffer { const out = clone(buffer); for (let f = 0; f < buffer.frames; f++) { const l = out.data[f * 2] || 0, r = out.data[f * 2 + 1] || 0, m = (l + r) / 2, s = (l - r) / 2 * factor; out.data[f * 2] = m + s; out.data[f * 2 + 1] = m - s; } return out; }
export function extremePan(buffer: StereoBuffer, rateHz: number): StereoBuffer { const out = clone(buffer); for (let f = 0; f < buffer.frames; f++) { const p = Math.sin(2 * Math.PI * rateHz * f / buffer.sampleRate), l = out.data[f * 2] || 0, r = out.data[f * 2 + 1] || 0; out.data[f * 2] = l * Math.min(1, 1 - p); out.data[f * 2 + 1] = r * Math.min(1, 1 + p); } return out; }
export interface DelayOptions { timeMs: number; feedback: number; wet: number; }
export function feedbackDelay(buffer: StereoBuffer, o: DelayOptions): StereoBuffer { const out = clone(buffer), d = Math.max(1, Math.round(o.timeMs / 1000 * buffer.sampleRate)); for (let f = d; f < buffer.frames; f++) { const l = out.data[(f - d) * 2] || 0, r = out.data[(f - d) * 2 + 1] || 0; out.data[f * 2] += r * o.feedback * o.wet + l * o.wet; out.data[f * 2 + 1] += l * o.feedback * o.wet + r * o.wet; } return out; }
export interface ReverbOptions { wet: number; decay: number; predelayMs: number; }
export function simpleReverb(buffer: StereoBuffer, o: ReverbOptions): StereoBuffer { const out = clone(buffer), d = Math.max(1, Math.round(o.predelayMs / 1000 * buffer.sampleRate)), delays = [Math.round(.0297 * buffer.sampleRate), Math.round(.0371 * buffer.sampleRate), Math.round(.0411 * buffer.sampleRate)]; for (let f = 0; f < buffer.frames; f++) for (let c = 0; c < 2; c++) { let wet = 0; for (const delay of delays) { const src = f - d - delay; if (src >= 0) wet += buffer.data[src * 2 + c] * o.decay / delays.length; } out.data[f * 2 + c] += wet * o.wet; } return out; }
export interface SidechainOptions { beatFrames: number; duckDb: number; attackMs: number; releaseMs: number; offsetFrames?: number; }
export function sidechainDuck(buffer: StereoBuffer, o: SidechainOptions): StereoBuffer { const out = clone(buffer), a = Math.max(1, Math.round(o.attackMs / 1000 * buffer.sampleRate)), r = Math.max(1, Math.round(o.releaseMs / 1000 * buffer.sampleRate)), duck = dbToLinear(o.duckDb), offset = o.offsetFrames ?? 0; for (let f = 0; f < buffer.frames; f++) { const p = ((f - offset) % o.beatFrames + o.beatFrames) % o.beatFrames; const g = p < a ? 1 - (1 - duck) * p / a : p < a + r ? duck + (1 - duck) * (p - a) / r : 1; out.data[f * 2] *= g; out.data[f * 2 + 1] *= g; } return out; }
