import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { StemSeparationEngine, type SeparationRequest } from './stemSeparationEngine';
import { generateGoldStandardTrack, type GoldStandardTrack } from './goldStandard';
import { buildGoldStandardVariants, type VariantId } from './goldStandardVariants';
import { buildStemGroupMap, sumStems } from './stemGroupMapping';
import { evaluateStem, qualityLabel, qualityScore, sdr as sdrOf, type StemMetricsReport } from './metrics';
import { downmixMono } from './dsp';
import { encodeWavFloat32, encodeWavInt24, fileFingerprint, readWavFile } from './wavIo';
import type { StemId } from './types';
export interface StemIsolationGateOptions { engine: StemSeparationEngine; outputRoot: string; request?: Partial<SeparationRequest>; variant?: VariantId; seed?: number; writeAllVariants?: boolean; onLog?: (line: string) => void; }
export interface StemIsolationCheck { id: string; title: string; pass: boolean; detail: string; evidence?: Record<string, unknown>; }
export interface StemResultRow { stemId: StemId; isolation: number; bleed: number; transient: number; stereo: number; recombination: number; result: 'PASS'|'FAIL'; metrics: StemMetricsReport; qualityBreakdown: Record<string, number>; groundTruthComponents: StemId[]; }
export type ReleaseDecision = 'TECHNICAL_FAIL'|'TECHNICAL_PASS_QUALITY_FAIL'|'RELEASE_READY';
export interface StemIsolationGateReport { gate: 'STEM_ISOLATION'; part: 2; generatedAt: number; durationMs: number; variant: VariantId; modelId: string; fromTrainedModel: boolean; weightsRandom: boolean; originalHashBefore: string; originalHashAfter: string; technicalPass: boolean; qualityPass: boolean; releaseDecision: ReleaseDecision; checks: StemIsolationCheck[]; rows: StemResultRow[]; overallScore: number; overallLabel: string; recombinationErrorDb: number; segments: GoldStandardTrack['segments']; paths: { root: string; original: string; groundTruth: string; separated: string; recombined: string; metrics: string; report: string; }; }
function clamp10(v: number): number { return Math.max(0, Math.min(10, Number.isFinite(v) ? v : 0)); }
function scoreMetrics(metrics: StemMetricsReport): { isolation: number; bleed: number; transient: number; stereo: number } { const iso = clamp10(metrics.siSdrDb / 2), worst = metrics.bleed.length ? Math.max(...metrics.bleed.map((b) => b.bleedDb)) : -60; const bleed = clamp10(-worst / 3); const transient = metrics.transients.preserved ? 9 : clamp10(7 - metrics.transients.missingCount / Math.max(1, metrics.transients.referenceCount) * 10); const stereo = clamp10(metrics.stereo.becameMono ? 2 : 10 - Math.abs(metrics.stereo.widthDeltaDb) * .8 - Math.abs(metrics.stereo.correlationDelta) * 5); return { isolation: iso, bleed, transient, stereo }; }
function detectRandomWeights(metadata: { settings: { extras?: Record<string, string | number | boolean> }; events: { phase: string; detail?: string }[] }): boolean { if (metadata.settings.extras?.allowRandomWeights === true) return true; return metadata.events.some((event) => { if (event.phase !== 'backend-report' || !event.detail) return false; try { const report = JSON.parse(event.detail) as { weights?: string; reports?: { weights?: string }[] }; return report.weights === 'random' || report.reports?.some((x) => x.weights === 'random') === true; } catch { return false; } }); }
export async function runStemIsolationGate(options: StemIsolationGateOptions): Promise<StemIsolationGateReport> {
  const started = Date.now(), root = options.outputRoot, dirs = { root, original: path.join(root, 'original'), groundTruth: path.join(root, 'ground_truth'), separated: path.join(root, 'separated'), recombined: path.join(root, 'recombined'), metrics: path.join(root, 'metrics'), report: path.join(root, 'report') };
  await Promise.all(Object.values(dirs).map((dir) => mkdir(dir, { recursive: true }))); const checks: StemIsolationCheck[] = []; const add = (check: StemIsolationCheck) => { checks.push(check); options.onLog?.(`${check.pass ? '✓' : '✘'} ${check.id}: ${check.detail}`); };
  const track = generateGoldStandardTrack({ seed: options.seed }), variants = buildGoldStandardVariants(track), variantId = options.variant ?? 'A_clean', variant = variants.find((v) => v.id === variantId); if (!variant) throw new Error(`Unbekannte Testvariante: ${variantId}`);
  if (options.writeAllVariants) { const variantDir = path.join(root, 'variants'); await mkdir(variantDir, { recursive: true }); await Promise.all(variants.map((v) => writeFile(path.join(variantDir, `${v.id}.wav`), encodeWavFloat32(v.buffer.sampleRate, 2, v.buffer.data, v.buffer.frames)))); }
  for (const [id, data] of track.stems) await writeFile(path.join(dirs.groundTruth, `${id}.wav`), encodeWavInt24(track.sampleRate, 2, data, track.frames));
  const originalPath = path.join(dirs.original, 'mix.wav'); await writeFile(originalPath, encodeWavFloat32(variant.buffer.sampleRate, 2, variant.buffer.data, variant.buffer.frames)); const before = await fileFingerprint(originalPath);
  let summary; let failure: unknown;
  try { summary = await options.engine.separate({ inputPath: originalPath, profile: 'HIGH_QUALITY', trackName: 'gold_standard', ...(options.request ?? {}) }); } catch (error) { failure = error; }
  const after = await fileFingerprint(originalPath); const sameHash = before.sha256 === after.sha256 && before.size === after.size;
  add({ id: 'ORIGINAL_HASH_UNCHANGED', title: 'Original-Hash vorher == nachher', pass: sameHash, detail: sameHash ? `sha256 unverändert (${before.sha256.slice(0, 16)}…)` : 'Original verändert – HARD FAIL', evidence: { before: before.sha256, after: after.sha256 } });
  add({ id: 'SEPARATION_COMPLETED', title: 'Separation abgeschlossen', pass: summary?.status === 'COMPLETED', detail: summary ? `Status ${summary.status}` : `Fehler: ${failure instanceof Error ? failure.message : String(failure)}` });
  if (!summary || summary.status !== 'COMPLETED') { const report = finalize(checks, [], started, variantId, before, after, dirs, track, 'unknown', false, false, Number.NaN); await writeReportFiles(report); return report; }
  const model = options.engine.registry.get(summary.metadata.settings.modelId), modelOrder = model?.stemOrder ?? summary.validation.stemOrder, fromTrainedModel = summary.validation.fromTrainedModel, weightsRandom = detectRandomWeights(summary.metadata), map = buildStemGroupMap(modelOrder, track.stemOrder);
  add({ id: 'STEM_GROUP_MAPPING', title: 'Ground-Truth-Quellen Modell-Stems zugeordnet', pass: map.unassigned.length === 0, detail: [...map.groups.entries()].map(([id, ids]) => `${id}={${ids.join('+')}}`).join(', '), evidence: { groups: Object.fromEntries(map.groups) } });
  const rows: StemResultRow[] = [], recombined = new Float32Array(track.frames * 2);
  for (const stem of summary.stems) {
    const ids = map.groups.get(stem.id) ?? [], reference = sumStems(track.stems, ids, track.frames, 2), audio = await readWavFile(stem.filePath); await copyFile(stem.filePath, path.join(dirs.separated, `${stem.id}.wav`));
    for (let i = 0; i < recombined.length; i++) recombined[i] += audio.data[i] || 0;
    const refSignal = { data: reference, channels: 2, frames: track.frames, sampleRate: track.sampleRate }, estSignal = { data: audio.data, channels: audio.channels, frames: audio.frames, sampleRate: audio.sampleRate }, others = [...map.groups.entries()].filter(([id]) => id !== stem.id).map(([id, gt]) => ({ id, signal: { data: sumStems(track.stems, gt, track.frames, 2), channels: 2, frames: track.frames, sampleRate: track.sampleRate } }));
    const metrics = evaluateStem(stem.id, refSignal, estSignal, others), scores = scoreMetrics(metrics), qs = qualityScore(metrics), recombination = sdrOf(downmixMono(reference, 2, track.frames), downmixMono(audio.data, audio.channels, Math.min(track.frames, audio.frames))), result = scores.isolation >= 4 && scores.bleed >= 3 && scores.transient >= 3 && scores.stereo >= 3 ? 'PASS' : 'FAIL';
    rows.push({ stemId: stem.id, ...scores, recombination: clamp10(recombination / 2), result, metrics, qualityBreakdown: qs.breakdown, groundTruthComponents: ids });
  }
  add({ id: 'ALL_STEMS_PRODUCED', title: 'Alle erwarteten Stems erzeugt', pass: rows.length === modelOrder.length, detail: `${rows.length}/${modelOrder.length} Stems` });
  const recombinedPath = path.join(dirs.recombined, 'mix.wav'); await writeFile(recombinedPath, encodeWavFloat32(track.sampleRate, 2, recombined, track.frames)); const original = await readWavFile(originalPath), recombinationErrorDb = sdrOf(downmixMono(original.data, original.channels, original.frames), downmixMono(recombined, 2, track.frames)), recombinationLimit = fromTrainedModel ? 6 : 20;
  add({ id: 'RECOMBINATION_MATCHES_ORIGINAL', title: 'Recombined Mix nahe am Original', pass: Number.isFinite(recombinationErrorDb) && recombinationErrorDb >= recombinationLimit, detail: `SDR=${recombinationErrorDb.toFixed(1)} dB (Limit ${recombinationLimit} dB)`, evidence: { recombinationErrorDb, recombinationLimit } });
  add({ id: 'FROM_TRAINED_MODEL', title: 'Trainiertes Modell statt Double/Zufallsgewichte', pass: fromTrainedModel && !weightsRandom, detail: fromTrainedModel && !weightsRandom ? `Modell ${summary.metadata.settings.modelId}` : weightsRandom ? 'weights=random' : 'pipeline_double – Qualitäts-Gate bleibt geschlossen' });
  const technical = checks.filter((x) => x.id !== 'FROM_TRAINED_MODEL').every((x) => x.pass), scoreValues = rows.map((r) => (r.isolation + r.bleed + r.transient + r.stereo + r.recombination) / 5), overall = scoreValues.length ? scoreValues.reduce((a, b) => a + b, 0) / scoreValues.length : 0, quality = technical && fromTrainedModel && !weightsRandom && rows.every((x) => x.result === 'PASS') && overall >= 8.5;
  add({ id: 'STEM_ISOLATION_GATE', title: 'Stem Isolation Gate: alle Bedingungen', pass: quality, detail: `Gesamtscore ${overall.toFixed(2)}/10; alle Stems PASS: ${rows.every((x) => x.result === 'PASS')}` });
  const report = finalize(checks, rows, started, variantId, before, after, dirs, track, summary.metadata.settings.modelId, fromTrainedModel, weightsRandom, recombinationErrorDb); await writeReportFiles(report); return report;
}
function finalize(checks: StemIsolationCheck[], rows: StemResultRow[], started: number, variant: VariantId, before: { sha256: string; size: number }, after: { sha256: string; size: number }, paths: StemIsolationGateReport['paths'], track: GoldStandardTrack, modelId: string, trained: boolean, random: boolean, recombinationErrorDb: number): StemIsolationGateReport { const technicalPass = checks.filter((x) => x.id !== 'FROM_TRAINED_MODEL' && x.id !== 'STEM_ISOLATION_GATE').every((x) => x.pass), values = rows.map((r) => (r.isolation + r.bleed + r.transient + r.stereo + r.recombination) / 5), overall = values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0, qualityPass = checks.find((x) => x.id === 'STEM_ISOLATION_GATE')?.pass === true; const releaseDecision: ReleaseDecision = technicalPass && qualityPass ? 'RELEASE_READY' : technicalPass ? 'TECHNICAL_PASS_QUALITY_FAIL' : 'TECHNICAL_FAIL'; return { gate: 'STEM_ISOLATION', part: 2, generatedAt: started, durationMs: Date.now() - started, variant, modelId, fromTrainedModel: trained, weightsRandom: random, originalHashBefore: before.sha256, originalHashAfter: after.sha256, technicalPass, qualityPass, releaseDecision, checks, rows, overallScore: overall, overallLabel: qualityLabel(overall), recombinationErrorDb, segments: track.segments, paths }; }
async function writeReportFiles(report: StemIsolationGateReport): Promise<void> { await writeFile(path.join(report.paths.metrics, 'metrics.json'), JSON.stringify(report, null, 2)); await writeFile(path.join(report.paths.report, 'report.html'), renderHtmlReport(report)); await writeFile(path.join(report.paths.root, 'metadata.json'), JSON.stringify({ gate: report.gate, part: report.part, generatedAt: new Date(report.generatedAt).toISOString(), durationMs: report.durationMs, variant: report.variant, modelId: report.modelId, fromTrainedModel: report.fromTrainedModel, weightsRandom: report.weightsRandom, releaseDecision: report.releaseDecision, technicalPass: report.technicalPass, qualityPass: report.qualityPass, overallScore: report.overallScore, overallLabel: report.overallLabel, originalHashBefore: report.originalHashBefore, originalHashAfter: report.originalHashAfter, segments: report.segments }, null, 2)); }
function htmlEscape(value: unknown): string { return String(value).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!)); }
function renderHtmlReport(report: StemIsolationGateReport): string { const rows = report.rows.map((r) => `<tr class="${r.result === 'PASS' ? 'pass' : 'fail'}"><td>${htmlEscape(r.stemId)}</td><td>${r.isolation.toFixed(1)}</td><td>${r.bleed.toFixed(1)}</td><td>${r.transient.toFixed(1)}</td><td>${r.stereo.toFixed(1)}</td><td>${r.recombination.toFixed(1)}</td><td>${r.result}</td></tr>`).join(''); const checks = report.checks.map((c) => `<li class="${c.pass ? 'pass' : 'fail'}"><strong>${htmlEscape(c.id)}</strong>: ${htmlEscape(c.detail)}</li>`).join(''); return `<!doctype html><html lang="de"><head><meta charset="utf-8"><title>Stem Isolation Gate Report</title><style>body{font-family:system-ui;margin:2rem;background:#0e0e12;color:#eee}table{border-collapse:collapse;width:100%}th,td{border:1px solid #333;padding:.5rem}tr.pass td:last-child,.pass{color:#7cfc98}.fail{color:#ff6b6b}.badge{padding:.3rem .8rem;border-radius:6px;font-weight:bold;background:#8a6d1a}</style></head><body><h1>Stem Isolation Gate — Report</h1><p>Variante: <strong>${htmlEscape(report.variant)}</strong> · Modell: <strong>${htmlEscape(report.modelId)}</strong> · trainiert: <strong>${report.fromTrainedModel}</strong> · weights=random: <strong>${report.weightsRandom}</strong></p><p>Release-Entscheidung: <span class="badge">${htmlEscape(report.releaseDecision)}</span></p><p>Gesamtscore: <strong>${report.overallScore.toFixed(2)}/10</strong> (${htmlEscape(report.overallLabel)})</p><p>Original-Hash: ${report.originalHashBefore === report.originalHashAfter ? 'unverändert ✓' : 'VERÄNDERT ✘'}</p><h2>Ergebnistabelle</h2><table><thead><tr><th>Stem</th><th>Isolation</th><th>Bleed</th><th>Transient</th><th>Stereo</th><th>Recombination</th><th>Result</th></tr></thead><tbody>${rows || '<tr><td colspan="7">keine Stems</td></tr>'}</tbody></table><h2>Checks</h2><ul>${checks}</ul><h2>Segmente</h2><ul>${report.segments.map((s) => `<li>${s.startSeconds}-${s.endSeconds}s — ${htmlEscape(s.title)}: ${htmlEscape(s.description)}</li>`).join('')}</ul></body></html>`; }
