/**
 * @license
 * Verifies the compiler-free SQLCipher reader used by the Windows desktop app:
 * the pure-JavaScript codec, the read-only database reader on top of it and the
 * synthetic Rekordbox fixtures that mirror the real schemas.
 *
 * The fixtures in tests/fixtures/ are generated by
 * tools/generate-sqlcipher-fixtures.py (real SQLCipher files, artificial data)
 * so this suite needs neither SQLCipher nor a C compiler.
 *
 * Run with: node tests/sqlcipher-js-reader.test.mjs
 */

import assert from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));
const fixture = (...parts) => path.join(here, 'fixtures', ...parts);

const { decryptDatabase, reserveSize, CIPHER_CANDIDATES, looksLikeSqliteHeader } = require(
  '../electron/sqlcipherCodec.cjs'
);
const { readRekordboxDatabase, detectDbType, getMasterDbKey, getOneLibraryKey } = require(
  '../electron/dbReader.cjs'
);

let passed = 0;
const checks = [];
const failures = [];

/** Runs one assertion block, collects the result and keeps going on failure. */
async function check(name, fn) {
  try {
    await fn();
    passed += 1;
    checks.push(`  ✓ ${name}`);
  } catch (error) {
    checks.push(`  ✗ ${name}\n      ${error.message}`);
    failures.push(error);
  }
}

console.log('\n  SQLCipher – reiner JavaScript-Leser (Windows-Build ohne Visual Studio)');

// ─── page layout constants ──────────────────────────────────────────────────
const v4 = CIPHER_CANDIDATES.find((candidate) => candidate.id === 'SQLCipher v4');
const v3 = CIPHER_CANDIDATES.find((candidate) => candidate.id === 'SQLCipher v3');

await check('Reserve-Größe: v4 = 80 Bytes (IV 16 + HMAC-SHA512 64), v3 = 48 Bytes', () => {
  assert.strictEqual(v4.pageSize, 4096);
  assert.strictEqual(v4.kdfIter, 256000);
  assert.strictEqual(reserveSize(v4), 80);
  assert.strictEqual(reserveSize(v3), 48);
  assert.strictEqual(reserveSize({ ...v3, hmac: false }), 16);
});

// ─── decryption of the real SQLCipher fixtures ──────────────────────────────
const masterV4 = decryptDatabase(fs.readFileSync(fixture('rekordbox6', 'master.db')), getMasterDbKey());

await check('master.db (SQLCipher v4) wird entschlüsselt und erhält den SQLite-Marker', () => {
  assert.strictEqual(masterV4.ok, true, masterV4.reason + ' | ' + (masterV4.tried || []).join('; '));
  assert.strictEqual(masterV4.config.id, 'SQLCipher v4');
  assert.strictEqual(masterV4.pageSize, 4096);
  assert.strictEqual(masterV4.data.subarray(0, 16).toString('latin1'), 'SQLite format 3\0');
  assert.strictEqual(looksLikeSqliteHeader(masterV4.data).valid, true);
  // The reserve value of the source file is kept, so usable page size stays 4016.
  assert.strictEqual(masterV4.data[20], 80);
});

await check('Das entschlüsselte Abbild ist eine gültige SQLite-Datei (Seitenanzahl + Seite 1)', () => {
  assert.ok(masterV4.pageCount >= 2, 'erwartet mehrere Seiten');
  assert.strictEqual(masterV4.data.length % 4096, 0);
  // freelist / schema cookie area must not be zeroed out
  assert.ok(masterV4.data.readUInt32BE(28) > 0);
});

await check('exportLibrary.db (OneLibrary) mit eigenem Schlüssel', () => {
  const result = decryptDatabase(fs.readFileSync(fixture('onelibrary', 'exportLibrary.db')), getOneLibraryKey());
  assert.strictEqual(result.ok, true, result.reason + ' | ' + (result.tried || []).join('; '));
  // The other passphrase must not unlock it.
  const wrong = decryptDatabase(fs.readFileSync(fixture('onelibrary', 'exportLibrary.db')), getMasterDbKey());
  assert.strictEqual(wrong.ok, false);
});

await check('Ältere Konfiguration (SQLCipher v3) wird über das Profil-Raten erkannt', () => {
  const result = decryptDatabase(fs.readFileSync(fixture('legacy-v3', 'master.db')), getMasterDbKey());
  assert.strictEqual(result.ok, true, result.reason + ' | ' + (result.tried || []).join('; '));
  assert.strictEqual(result.config.id, 'SQLCipher v3');
  assert.strictEqual(result.pageSize, 1024);
});

await check('Falscher Schlüssel wird über die HMAC-Prüfung verworfen', () => {
  const result = decryptDatabase(fs.readFileSync(fixture('rekordbox6', 'master.db')), '0'.repeat(64));
  assert.strictEqual(result.ok, false);
  assert.ok(
    (result.tried || []).some((entry) => /HMAC/.test(entry)),
    'Erwartet einen HMAC-Fehler, bekam: ' + (result.tried || []).join('; ')
  );
});

await check('Klartext-SQLite wird unverändert durchgereicht', () => {
  const result = decryptDatabase(fs.readFileSync(fixture('plaintext', 'master.db')), getMasterDbKey());
  assert.strictEqual(result.ok, true, result.reason);
  assert.strictEqual(result.config.id, 'Klartext-SQLite');
});

// ─── the reader the Electron main process uses ──────────────────────────────
const masterResult = await readRekordboxDatabase(fixture('rekordbox6', 'master.db'));

await check('readRekordboxDatabase liefert Zeilen im XML-Vertrag (engine unabhängig)', () => {
  assert.strictEqual(masterResult.available, true, masterResult.reason);
  assert.strictEqual(masterResult.dbType, 'MASTER_DB');
  assert.ok(['NATIVE_SQLCIPHER', 'JS_SQLCIPHER'].includes(masterResult.engine), `engine=${masterResult.engine}`);
  assert.strictEqual(masterResult.rows.content.length, 2);
  const track = masterResult.rows.content[0];
  assert.strictEqual(track.Title, 'Obsidian Voltage (Club Mix)');
  assert.strictEqual(track.BPM, 12800);
  assert.strictEqual(track.Length, 240000);
  assert.strictEqual(track.Rating, 255);
  // Windows paths survive the round trip unchanged (read-only source).
  assert.strictEqual(track.FolderPath, 'C:\\Music\\Rekordbox');
  assert.strictEqual(track.FileNameL, 'Obsidian Voltage.wav');
  assert.match(track.AnalysisDataPath, /ANLZ/);
  assert.strictEqual(masterResult.rows.cues.length, 4);
  assert.strictEqual(masterResult.rows.keys[0].ScaleName, '8A');
  assert.strictEqual(masterResult.stats.tracks, 2);
  assert.strictEqual(masterResult.stats.cues, 4);
});

await check('Unicode (deutsche Umlaute) bleibt beim Lesen erhalten', () => {
  const titles = masterResult.rows.content.map((row) => row.Title);
  assert.ok(titles.some((title) => /Voltage/.test(title)), 'Titel fehlen');
  const artists = masterResult.rows.artists.map((row) => row.Name);
  assert.ok(artists.includes('Zwilling & Brüder'), `artisten=${artists.join(', ')}`);
});

await check('OneLibrary-Lesepfad (content/cue camelCase)', async () => {
  const result = await readRekordboxDatabase(fixture('onelibrary', 'exportLibrary.db'));
  assert.strictEqual(result.available, true, result.reason);
  assert.strictEqual(result.dbType, 'ONE_LIBRARY');
  assert.strictEqual(result.rows.content.length, 1);
  assert.strictEqual(result.rows.content[0].title, 'Neon Glut');
  assert.strictEqual(result.rows.content[0].bpmx100, 12650);
  assert.strictEqual(result.rows.cues.length, 3);
  assert.strictEqual(result.rows.playlists[0].name, 'USB Set');
});

await check('Unbekannter Dateiname wird abgewiesen, ohne die Datei zu öffnen', () => {
  assert.strictEqual(detectDbType(fixture('rekordbox6', 'master.db')), 'MASTER_DB');
  assert.strictEqual(detectDbType('D:\\Musik\\sound.db'), null);
});

await check('Fremde .db-Datei liefert nachvollziehbare Meldung statt Absturz', async () => {
  const bogus = path.join(here, '.bogus-master.db');
  fs.writeFileSync(bogus, Buffer.concat([Buffer.from('SQLite format 3\0', 'latin1'), Buffer.alloc(4096, 0x41)]));
  try {
    const result = await readRekordboxDatabase(bogus);
    assert.ok(!result.available || !Array.isArray(result.rows?.content) || result.rows.content.length === 0);
    if (!result.available) assert.ok(typeof result.reason === 'string' && result.reason.length > 10);
  } finally {
    fs.rmSync(bogus, { force: true });
  }
});

console.log(checks.join('\n'));
if (failures.length > 0) {
  console.error(`\n  ${failures.length} von ${checks.length} Prüfungen fehlgeschlagen\n`);
  process.exit(1);
}
console.log(`\n  ${passed} Prüfungen bestanden\n`);
