const { app, BrowserWindow, ipcMain, dialog } = require('electron');
const path = require('path');
const { exec } = require('child_process');
const fs = require('fs');

function createWindow() {
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false, // For easier IPC communication in this prototype
    },
  });

  // Load the React app from localhost during development, or from built files in production
  if (process.env.NODE_ENV === 'development') {
    win.loadURL('http://localhost:5173'); // Assuming Vite default port
    win.webContents.openDevTools();
  } else {
    // In production, the React app should be built into a 'dist' folder
    win.loadFile(path.join(__dirname, '../dist/index.html'));
  }
}

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// IPC handler for separating stems using Python Demucs/audio-separator
ipcMain.handle('separate-stems', async (event, inputFilePath) => {
    return new Promise((resolve, reject) => {
        // Output directory for the stems
        const outputDir = path.join(app.getPath('userData'), 'separated_stems');
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }

        console.log(`Starting separation for: ${inputFilePath}`);
        console.log(`Output directory: ${outputDir}`);

        // We assume Python and a separation library (like demucs or audio-separator) is installed on the host system.
        // For this example, we'll try to call 'audio-separator' which we used in the Colab tests.
        // It needs to be installed globally on the user's Windows machine: `pip install audio-separator`
        
        // Command to run the separation.
        // Note: For a true standalone desktop app, you would bundle a compiled Python executable
        // or a dedicated C++ binary (like demucs.cpp) with the Electron app.
        const command = `audio-separator "${inputFilePath}" --output_dir "${outputDir}" --output_format WAV`;

        exec(command, (error, stdout, stderr) => {
            if (error) {
                console.error(`Error executing separator: ${error}`);
                console.error(stderr);
                reject(error.message);
                return;
            }
            
            console.log(`Separation finished. Output: ${stdout}`);
            
            // Expected output files from audio-separator (depends on the model used, assuming default 2-stem for now, but usually it's 4-stem or 2-stem)
            // You'll need to adapt this logic to find the exact filenames generated by the specific model you choose.
            
            fs.readdir(outputDir, (err, files) => {
                if (err) {
                    reject(err);
                    return;
                }
                
                // Get the base filename without extension to filter relevant files
                const baseName = path.parse(inputFilePath).name;
                const generatedFiles = files.filter(f => f.includes(baseName) && f.endsWith('.wav'));
                
                const stems = generatedFiles.map(file => path.join(outputDir, file));
                
                resolve(stems);
            });
        });
    });
});
