#!/usr/bin/env python3
"""Trains the EDMSMOKE BS-RoFormer checkpoint for the Stem Isolation Gate (TEIL 2).

Purpose: the trained MUSDB18-HQ checkpoint (`model_bs_roformer_ep_17_sdr_9.6568.ckpt`)
is a ~1 GB release asset that is not always fetchable (offline CI, restricted
egress). The gate, however, needs a checkpoint whose weights are really
optimized for the test material to prove the whole path:

    dataset -> training -> checkpoint -> adapter (weights="checkpoint") -> SI-SDR

This script trains the tiny architecture from `edmsmoke_bs_roformer.yaml` on
synthetic EDM material (mix + ground truth stems generated by
`src/stems/testAudioGenerator.ts` and written as WAV by `scripts/trainSmokeCheckpoint.ts`)
with a plain waveform L1 loss inside the reference implementation's own
forward pass (ZFTurbo BSRoformer, `model(mix, target=stems)`).

The result is a SMOKE checkpoint for a SYNTHETIC domain. It is never a
replacement for the MUSDB18-HQ model and must never ship as one. The output
format is deliberately identical to an MSST checkpoint (`{"state_dict": ...}`)
so the production adapter accepts it without special cases.

Usage (driven by `scripts/trainSmokeCheckpoint.ts`, which prepares the data):
    python3 python/train_smoke_checkpoint.py \
        --config tests/fixtures/bsroformer/edmsmoke_bs_roformer.yaml \
        --reference-source-dir ~/.cache/airdox-stems/vendor/msst \
        --data-dir ~/.cache/airdox-stems/edmsmoke-data \
        --steps 250 --chunk-size 65536 --seed 1234 \
        --out ~/.cache/airdox-stems/checkpoints/model_bs_roformer_edmsmoke.ckpt
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import random
import sys
import time
from pathlib import Path

EXIT_OK = 0
EXIT_BAD_ARGS = 2
EXIT_MODEL = 3
EXIT_IO = 4


def emit(payload: dict) -> None:
    sys.stdout.write(json.dumps(payload, ensure_ascii=False) + "\n")
    sys.stdout.flush()


def parse_args(argv):
    parser = argparse.ArgumentParser(description="EDMSMOKE BS-RoFormer trainer")
    parser.add_argument("--config", required=True)
    parser.add_argument("--reference-source-dir", required=True)
    parser.add_argument("--data-dir", required=True)
    parser.add_argument("--steps", type=int, default=250)
    parser.add_argument("--chunk-size", type=int, default=65536)
    parser.add_argument("--seed", type=int, default=1234)
    parser.add_argument("--learning-rate", type=float, default=3e-4)
    parser.add_argument("--log-every", type=int, default=10)
    parser.add_argument("--start-checkpoint", default="", help="Checkpoint zum Weitertrainieren (state_dict)")
    parser.add_argument("--out", required=True)
    return parser.parse_args(argv)


def load_adapter_module(adapter_path: Path):
    """Imports the production adapter to reuse `load_config_dict` + `build_model`."""
    spec = importlib.util.spec_from_file_location("bsroformer_inference", adapter_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Adapter nicht ladbar: {adapter_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_manifest(data_dir: Path) -> dict:
    manifest_path = data_dir / "manifest.json"
    with manifest_path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def main(argv) -> int:
    args = parse_args(argv)
    started = time.time()
    repo_root = Path(__file__).resolve().parent.parent

    try:
        import numpy as np
        import soundfile as sf
        import torch
    except Exception as error:  # noqa: BLE001
        emit({"type": "error", "code": "BACKEND_UNAVAILABLE", "message": f"PyTorch/numpy/soundfile fehlen: {error}"})
        return EXIT_MODEL

    try:
        adapter = load_adapter_module(repo_root / "python" / "bsroformer_inference.py")
        config = adapter.load_config_dict(args.config)
        model = adapter.build_model("bs_roformer", config, args.reference_source_dir, "cpu", "f32")
    except Exception as error:  # noqa: BLE001
        emit({"type": "error", "code": "MODEL_CORRUPT", "message": f"Architektur nicht aufbaubar: {error}"})
        return EXIT_MODEL

    instruments = list(getattr(config.training, "instruments", []) or [])
    if not instruments:
        emit({"type": "error", "code": "MODEL_CORRUPT", "message": "config.training.instruments fehlt"})
        return EXIT_MODEL

    try:
        manifest = load_manifest(Path(args.data_dir))
        samples = manifest["samples"]
        if not samples:
            raise RuntimeError("manifest enthaelt keine Samples")
    except Exception as error:  # noqa: BLE001
        emit({"type": "error", "code": "DATA_INVALID", "message": f"Dataset nicht lesbar: {error}"})
        return EXIT_IO

    random.seed(args.seed)
    torch.manual_seed(args.seed)
    torch.use_deterministic_algorithms(False)
    if args.start_checkpoint:
        state = torch.load(args.start_checkpoint, map_location="cpu", weights_only=False)
        if isinstance(state, dict) and "state_dict" in state:
            state = state["state_dict"]
        model.load_state_dict(state)
        emit({"type": "log", "level": "info", "message": f"Weitertraining ab {args.start_checkpoint}"})
    model.train()

    optimizer = torch.optim.Adam(model.parameters(), lr=args.learning_rate)
    chunk = int(args.chunk_size)
    losses = []

    emit({"type": "log", "level": "info", "message": f"Training startet: {args.steps} Schritte, Chunk {chunk}, {len(samples)} Samples, instruments={instruments}"})

    for step in range(1, args.steps + 1):
        sample = samples[random.randrange(len(samples))]
        try:
            mix, rate = sf.read(sample["mix"], dtype="float32", always_2d=True)
        except Exception as error:  # noqa: BLE001
            emit({"type": "error", "code": "DATA_INVALID", "message": f"{sample['mix']}: {error}"})
            return EXIT_IO
        stems = {}
        for stem_id in instruments:
            data, _ = sf.read(sample["stems"][stem_id], dtype="float32", always_2d=True)
            stems[stem_id] = data
        total = min(mix.shape[0], min(stem.shape[0] for stem in stems.values()))
        if total <= chunk:
            offset = 0
        else:
            offset = random.randrange(total - chunk)
        window = slice(offset, offset + chunk)

        mix_tensor = torch.from_numpy(mix[window].T).float().unsqueeze(0)  # (1, 2, S)
        target = torch.stack(
            [torch.from_numpy(stems[stem_id][window].T).float() for stem_id in instruments], dim=0
        ).unsqueeze(0)  # (1, num_stems, 2, S)

        optimizer.zero_grad(set_to_none=True)
        loss = model(mix_tensor, target=target)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        optimizer.step()
        losses.append(float(loss.detach()))

        if step % max(1, args.log_every) == 0 or step == 1 or step == args.steps:
            recent = losses[-max(1, args.log_every):]
            emit({
                "type": "progress",
                "fraction": step / args.steps,
                "step": step,
                "lossMean": round(sum(recent) / len(recent), 6),
                "lossLast": round(losses[-1], 6),
            })

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "state_dict": model.state_dict(),
            "format": "edmsmoke-v1",
            "steps": args.steps,
            "seed": args.seed,
            "instruments": instruments,
            "finalLoss": losses[-1] if losses else None,
        },
        out_path,
    )
    emit({
        "type": "done",
        "checkpoint": str(out_path),
        "steps": args.steps,
        "finalLoss": losses[-1] if losses else None,
        "lossFirst5": round(sum(losses[:5]) / max(1, len(losses[:5])), 6),
        "lossLast10Mean": round(sum(losses[-10:]) / max(1, len(losses[-10:])), 6),
        "seconds": round(time.time() - started, 1),
    })
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
